# docker build . -t stswoon/python-nodejs-silero:python3.9-nodejs18-silero0.4.11
# docker login
# docker image push stswoon/python-nodejs-silero:python3.9-nodejs18-silero0.4.11

FROM nikolaik/python-nodejs:python3.9-nodejs18-slim
RUN pip install silero==0.4.1
